version: "3"
services:
  t_task:
    build: .
    ports:
      - "1999:80"
    volumes:
      - ./:/var/www/html/
    links:
      - books_mysql

  books_mysql:
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: books
      MYSQL_USER: books
      MYSQL_PASSWORD: 123456
    volumes:
      - mysql-db:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8999:8080

volumes:
  mysql-db: